import type { LevelDef } from "./types";

/**
 * 48-level campaign. All levels verified solvable:
 *   npm run verify-levels
 */
export const LEVELS: LevelDef[] = [
  // ——— Ch1 Tutorial ———
  {
    id: 1,
    name: "First Push",
    objective: "Push the crystal onto the orange goal.",
    parMoves: 6,
    map: ["  #####  ", "  #...#  ", "  #.$.#  ", "  #@.G#  ", "  #####  "],
  },
  {
    id: 2,
    name: "Twin Crystals",
    objective: "Both crystals must rest on goals.",
    parMoves: 18,
    map: [
      "########",
      "#......#",
      "#.$..$.#",
      "#..@...#",
      "#.G..G.#",
      "#......#",
      "########",
    ],
  },
  {
    id: 3,
    name: "The Hall",
    objective: "Don't trap the crate in a corner.",
    parMoves: 24,
    map: [
      "##########",
      "#@.......#",
      "#.######.#",
      "#.$....G.#",
      "#.######.#",
      "#........#",
      "##########",
    ],
  },
  {
    id: 4,
    name: "Plate & Door",
    objective: "Step on the plate to open the door, then park the crystal on the goal.",
    parMoves: 16,
    map: [
      // Door is the only way into the goal alcove — plate is required (no bypass).
      "#############",
      "#@..........#",
      "#.$.....P...#",
      "#......##D###",
      "#......#.G.##",
      "#......#...##",
      "#############",
    ],
    doors: [{ x: 9, y: 3, plates: [{ x: 8, y: 2 }] }],
  },
  {
    id: 5,
    name: "Key Room",
    // Unlike L4's vertical alcove: horizontal corridor; plate is upstairs, then push through the gate.
    objective: "Hit the plate upstairs, then push the crystal through the gate to the goal.",
    parMoves: 34,
    map: [
      "###############",
      "#@............#",
      "#.$......P....#",
      "#....##########",
      "#....D.......G#",
      "#....##########",
      "###############",
    ],
    doors: [{ x: 5, y: 4, plates: [{ x: 9, y: 2 }] }],
  },
  {
    id: 6,
    name: "Ice Rink",
    // Crate is sealed in a one-way ice lane: only a right push reaches G (slides on I).
    // Outer floor is for the player only — crystal cannot walk around the ice.
    objective: "Push the crystal onto the ice — it slides until something stops it.",
    parMoves: 10,
    map: [
      "###########",
      "#@........#",
      "#.#########",
      "#..$IIIIIG#",
      "#.#########",
      "#.........#",
      "###########",
    ],
  },
  {
    id: 7,
    name: "Portal Hop",
    // Sealed wall — only A→B reaches the crystal (no gap walkaround).
    objective: "Walk into portal A to appear at B.",
    parMoves: 12,
    map: [
      "###########",
      "#@...A....#",
      "#.........#",
      "###########",
      "    #B#    ",
      "    #$#    ",
      "    #G#    ",
      "    ###    ",
    ],
  },
  {
    id: 8,
    name: "Mirror",
    objective: "Two crates, two goals — keep symmetry in mind.",
    parMoves: 40,
    map: [
      "  #######  ",
      " ##.....## ",
      "##.$...$.##",
      "#....@....#",
      "##.G...G.##",
      " ##.....## ",
      "  #######  ",
    ],
  },

  // ——— Ch2 ———
  {
    id: 9,
    name: "Airlocks",
    objective: "Two doors in a row. Each has its own plate.",
    parMoves: 48,
    map: [
      // Stacked gates on col 8 + roomy alcove so the crate can be steered onto G.
      "###############",
      "#@............#",
      "#.$......P....#",
      "#.............#",
      "########D######",
      "#......P......#",
      "#.....##D##...#",
      "#.....#.G.#...#",
      "#.....#...#...#",
      "###############",
    ],
    doors: [
      { x: 8, y: 4, plates: [{ x: 9, y: 2 }] },
      { x: 8, y: 6, plates: [{ x: 7, y: 5 }] },
    ],
  },
  {
    id: 10,
    name: "Ice Maze",
    // L-shaped ice corridors + a dead-end spur. G sealed from below so the
    // crystal cannot walk around on dry floor — sliding is required.
    objective: "Slide the crystal through the ice corridors. Wrong turns overshoot.",
    parMoves: 18,
    map: [
      "###############",
      "#@............#",
      "#....##########",
      "#...$##########",
      "#...I##########",
      "#...IIII#######",
      "#...I..I#######",
      "#...I..IIIIIG##",
      "#...###########",
      "#.............#",
      "###############",
    ],
  },
  {
    id: 11,
    name: "Portal Drop",
    // Crystal is below; only portal reaches the vault (crates never teleport).
    objective: "Use the portal to reach the lower vault.",
    parMoves: 14,
    map: [
      "##############",
      "#@....A......#",
      "#............#",
      "##############",
      "     #B#      ",
      "   ###$###    ",
      "   #..G..#    ",
      "   #######    ",
    ],
  },
  {
    id: 12,
    name: "Architect",
    // Plate latches the vault door; portal is the only way down to both crystals.
    objective: "Hit the plate, portal in, park both crystals.",
    parMoves: 28,
    map: [
      "################",
      "#@.......A.....#",
      "#........P.....#",
      "################",
      "       #B#      ",
      "     ###D###    ",
      "     #.$G$.#    ",
      "     #.....#    ",
      "     #######    ",
    ],
    doors: [{ x: 8, y: 5, plates: [{ x: 9, y: 2 }] }],
  },
  {
    id: 13,
    name: "Side Step",
    objective: "Give yourself room before the final push.",
    parMoves: 20,
    map: [
      "#########",
      "#@......#",
      "#..$....#",
      "#.......#",
      "#....G..#",
      "#.......#",
      "#########",
    ],
  },
  {
    id: 14,
    name: "Triple",
    objective: "Three crystals, three goals.",
    parMoves: 45,
    map: [
      "##########",
      "#@.......#",
      "#.$$.$...#",
      "#........#",
      "#.G.G.G..#",
      "#........#",
      "##########",
    ],
  },
  {
    id: 15,
    name: "Open Gate",
    objective: "Plate opens the gate to the goal alcove.",
    parMoves: 30,
    map: [
      "###########",
      "#@........#",
      "#.$..P....#",
      "#.........#",
      "####D######",
      "#...G.....#",
      "#.........#",
      "###########",
    ],
    doors: [{ x: 4, y: 4, plates: [{ x: 5, y: 2 }] }],
  },
  {
    id: 16,
    name: "Storage",
    objective: "Park crates without blocking yourself in.",
    parMoves: 40,
    map: [
      "###########",
      "#@........#",
      "#.$....$..#",
      "#.........#",
      "#..G...G..#",
      "#.........#",
      "###########",
    ],
  },
  {
    id: 17,
    name: "Wide Court",
    objective: "Plenty of space — still think ahead.",
    parMoves: 25,
    map: [
      "##########",
      "#@.......#",
      "#..$.....#",
      "#........#",
      "#.....G..#",
      "#........#",
      "##########",
    ],
  },
  {
    id: 18,
    name: "Vault Door",
    objective: "Open the vault, deliver both crystals.",
    parMoves: 55,
    map: [
      // One solid wall-gate (framed) + open bay — two crates need space, not a second choke.
      "###############",
      "#@............#",
      "#.$$....P.....#",
      "#.............#",
      "########D######",
      "#.............#",
      "#....G.....G..#",
      "#.............#",
      "###############",
    ],
    doors: [{ x: 8, y: 4, plates: [{ x: 8, y: 2 }] }],
  },

  // ——— Ch3 Ice & portals ———
  {
    id: 19,
    name: "Skate Push",
    // Stand on ice left of the crystal, push once — it skates the whole runway to G.
    // Sealed corridor: no dry path to the goal (G only reachable via ice slide).
    objective: "Stand on the ice and push — the crystal skates until it stops.",
    parMoves: 12,
    map: [
      "################",
      "#@.............#",
      "#.##############",
      "#.I$IIIIIIIIIIG#",
      "#.##############",
      "#..............#",
      "################",
    ],
  },
  {
    id: 20,
    name: "Ring Ice",
    // Ice forms an O-ring around a vault. Gate is offset from the crystal —
    // ride the ring, stop aligned with the gap, then exit inward to G.
    objective: "Ride the ice ring, then exit into the vault at the right moment.",
    parMoves: 24,
    map: [
      "#############",
      "#@..........#",
      "#.IIIIIIIII.#",
      "#.I#######I.#",
      "#.I#.....#I.#",
      "#.I#..G..#I.#",
      "#.I#.....#I.#",
      "#.I###.###I.#",
      "#.I$.....#I.#",
      "#.IIIIIIIII.#",
      "#...........#",
      "#############",
    ],
  },
  {
    id: 21,
    name: "Portal Pair",
    // Solid wall — must A→B to reach crystal and goal.
    objective: "Teleport past the wall, then finish the job.",
    parMoves: 12,
    map: [
      "###########",
      "#@..A.....#",
      "#.........#",
      "###########",
      "#....B....#",
      "#....$....#",
      "#....G....#",
      "###########",
    ],
  },
  {
    id: 22,
    name: "Frozen Gate",
    // Step plate (latches door), then skate the crystal through the open gate to G.
    // No dry path around the ice runway.
    objective: "Open the plate, then skate the crystal through the gate on ice.",
    parMoves: 14,
    map: [
      "################",
      "#@.............#",
      "#P.#############",
      "#..$IIIIIIIDG###",
      "#..............#",
      "################",
    ],
    doors: [{ x: 11, y: 3, plates: [{ x: 1, y: 2 }] }],
  },
  {
    id: 23,
    name: "Twin Bay",
    objective: "Two crates, two goals — open field.",
    parMoves: 40,
    map: [
      "############",
      "#@.........#",
      "#.$......$.#",
      "#..........#",
      "#..G....G..#",
      "#..........#",
      "############",
    ],
  },
  {
    id: 24,
    name: "Long Slide",
    objective: "One wrong direction and you overshoot.",
    parMoves: 28,
    map: [
      "############",
      "#@.........#",
      "#.IIIIIIII.#",
      "#........$.#",
      "#.IIIIIIII.#",
      "#.G........#",
      "############",
    ],
  },
  {
    id: 25,
    name: "Portal Key",
    // Plate lives only in the portal B pocket — must A→B to open the gate,
    // then return and push the crystal into the alcove.
    objective: "Portal to the plate, open the gate, then deliver the crystal.",
    parMoves: 28,
    map: [
      "##############",
      "#@....A......#",
      "#.$..........#",
      "#.......##D###",
      "#.......#.G.##",
      "#.......#...##",
      "##############",
      "     #B#      ",
      "     #P#      ",
      "     ###      ",
    ],
    doors: [{ x: 10, y: 3, plates: [{ x: 6, y: 8 }] }],
  },
  {
    id: 26,
    name: "Double Ice",
    // Two sealed ice runways — each crystal must skate to its goal.
    objective: "Two ice runways. Skate each crystal home.",
    parMoves: 18,
    map: [
      "###############",
      "#@............#",
      "#.#############",
      "#.$IIIIIG######",
      "#.#############",
      "#.$IIIIIG######",
      "#.#############",
      "#.............#",
      "###############",
    ],
  },
  {
    id: 27,
    name: "Detour",
    // Maze pocket — not the L3 hall clone.
    objective: "Walk the long way around the walls into the pocket.",
    parMoves: 18,
    map: [
      "##############",
      "#@...........#",
      "#.$..........#",
      "#.####...####",
      "#.#..#...#..#",
      "#.#..#G..#..#",
      "#.#..#####..#",
      "#.#.........#",
      "#.###########",
      "#............#",
      "##############",
    ],
  },
  {
    id: 28,
    name: "Chill Vault",
    // Vertical ice shaft through a plate-locked door (distinct from L22 horizontal).
    objective: "Drop the crystal down the ice shaft through the gate.",
    parMoves: 14,
    map: [
      "############",
      "#@.........#",
      "#P.#########",
      "#.$#########",
      "#.I#########",
      "#.I#########",
      "#.I####D####",
      "#.IIIIIG....",
      "############",
    ],
    doors: [{ x: 7, y: 6, plates: [{ x: 1, y: 2 }] }],
  },

  // ——— Ch4 Medium ———
  {
    id: 29,
    name: "Warehouse",
    objective: "Four crates — packing order matters.",
    parMoves: 70,
    map: [
      "############",
      "#@.........#",
      "#.$$...$$..#",
      "#..........#",
      "#.G.G.G.G..#",
      "#..........#",
      "############",
    ],
  },
  {
    id: 30,
    name: "Nested Gate",
    objective: "Open the outer gate, then the inner alcove — park both crystals.",
    parMoves: 65,
    map: [
      // Two stacked framed gates (col 8) + deep 3-wide bay for two crystals.
      "###############",
      "#@............#",
      "#.$$....P.....#",
      "#.............#",
      "########D######",
      "#......P......#",
      "#.....##D##...#",
      "#.....#...#...#",
      "#.....#...#...#",
      "#.....#G.G#...#",
      "#.....#...#...#",
      "###############",
    ],
    doors: [
      { x: 8, y: 4, plates: [{ x: 8, y: 2 }] },
      { x: 8, y: 6, plates: [{ x: 7, y: 5 }] },
    ],
  },
  {
    id: 31,
    name: "Lane Change",
    objective: "Shift lanes through the gaps.",
    parMoves: 40,
    map: [
      "##########",
      "#@.......#",
      "#..$.....#",
      "#..##....#",
      "#....##..#",
      "#.....G..#",
      "#........#",
      "##########",
    ],
  },
  {
    id: 32,
    name: "Relay",
    objective: "Open the door, score the crystal.",
    parMoves: 50,
    map: [
      "#############",
      "#@..........#",
      "#.$$...P....#",
      "#...........#",
      "######D######",
      "#.....G.....#",
      "#...........#",
      "#############",
    ],
    doors: [{ x: 6, y: 4, plates: [{ x: 7, y: 2 }] }],
  },
  {
    id: 33,
    name: "Ice Fork",
    // L-turn ice with a dead-end spur — different route from L10 maze.
    objective: "Choose the correct ice lane — the spur is a trap.",
    parMoves: 20,
    map: [
      "##############",
      "#@...........#",
      "#...##########",
      "#..$##########",
      "#..IIII#######",
      "#.....I#######",
      "#.....IIIIIG##",
      "#.....########",
      "#............#",
      "##############",
    ],
  },
  {
    id: 34,
    name: "Portal Bay",
    // Both crystals live in the lower bay — only A→B reaches them.
    objective: "Portal into the bay and park both crystals.",
    parMoves: 28,
    map: [
      "################",
      "#@......A......#",
      "#..............#",
      "################",
      "      #B#       ",
      "    ##.$G##     ",
      "    #.....#     ",
      "    ##.$G##     ",
      "    #######     ",
    ],
  },
  {
    id: 35,
    name: "U-Bend",
    // Pillar barrier with a tight goal pocket — must loop around, not push straight.
    objective: "Guide the crystal around the barrier into the pocket.",
    parMoves: 20,
    map: [
      "#############",
      "#@..........#",
      "#.$.........#",
      "#####...#####",
      "#...#...#...#",
      "#...#...#...#",
      "#...##G##...#",
      "#...........#",
      "#############",
    ],
  },
  {
    id: 36,
    name: "Two Keys",
    // Twin gates in one wall — not the stacked L9 airlock.
    objective: "Two plates open two doors on the way to the goal.",
    parMoves: 30,
    map: [
      "#################",
      "#@..............#",
      "#.$....P....P...#",
      "#...............#",
      "#####D#####D#####",
      "#...............#",
      "#.......G.......#",
      "#...............#",
      "#################",
    ],
    doors: [
      { x: 5, y: 4, plates: [{ x: 7, y: 2 }] },
      { x: 11, y: 4, plates: [{ x: 12, y: 2 }] },
    ],
  },
  {
    id: 37,
    name: "Corners",
    objective: "Bring distant crates home.",
    parMoves: 45,
    map: [
      "############",
      "#@.........#",
      "#.$......G.#",
      "#..........#",
      "#.G......$.#",
      "#..........#",
      "############",
    ],
  },
  {
    id: 38,
    name: "Ice & Iron",
    // Ice column then side door into the goal bay (not L22/L28 copy).
    objective: "Slide, open, deliver.",
    parMoves: 14,
    map: [
      "#############",
      "#@..........#",
      "#P.##########",
      "#.$##########",
      "#.I##########",
      "#.I######D###",
      "#.IIIIIIIG...",
      "#############",
    ],
    doors: [{ x: 9, y: 5, plates: [{ x: 1, y: 2 }] }],
  },

  // ——— Ch5 Expert ———
  {
    id: 39,
    name: "Gridlock",
    objective: "Three crates in a tight courtyard.",
    parMoves: 70,
    map: [
      "#########",
      "#@......#",
      "#.$$.$..#",
      "#.......#",
      "#.G.G.G.#",
      "#.......#",
      "#########",
    ],
  },
  {
    id: 40,
    name: "Cascade",
    objective: "Three doors — open them in order.",
    parMoves: 70,
    map: [
      // Three stacked gates on col 10 with landings + final alcove.
      "#################",
      "#@..............#",
      "#.$........P....#",
      "#...............#",
      "##########D######",
      "#........P......#",
      "#.......##D##...#",
      "#....P..#...#...#",
      "#.......##D##...#",
      "#.......#.G.#...#",
      "#.......#...#...#",
      "#################",
    ],
    doors: [
      { x: 10, y: 4, plates: [{ x: 11, y: 2 }] },
      { x: 10, y: 6, plates: [{ x: 9, y: 5 }] },
      { x: 10, y: 8, plates: [{ x: 5, y: 7 }] },
    ],
  },
  {
    id: 41,
    name: "Quad",
    objective: "Four crystals, four goals — open layout.",
    parMoves: 70,
    map: [
      "############",
      "#@.........#",
      "#.$$..$$...#",
      "#..........#",
      "#.G.G.G.G..#",
      "#..........#",
      "############",
    ],
  },
  {
    id: 42,
    name: "Spiral Path",
    // Wide twin locks (not L9 stack / not L36 twin spacing).
    objective: "Open both locks and park the crystal beyond them.",
    parMoves: 28,
    map: [
      "##################",
      "#@...............#",
      "#.$...P......P...#",
      "#................#",
      "######D######D####",
      "#................#",
      "#.........G......#",
      "##################",
    ],
    doors: [
      { x: 6, y: 4, plates: [{ x: 6, y: 2 }] },
      { x: 13, y: 4, plates: [{ x: 13, y: 2 }] },
    ],
  },
  {
    id: 43,
    name: "Portal Gauntlet",
    // Ice on approach + roomier vault (not L12 twin-crystal bay).
    objective: "Cross the ice, plate, portal — park the crystal.",
    parMoves: 22,
    map: [
      "#################",
      "#@........A.....#",
      "#.IIII....P.....#",
      "#################",
      "        #B#      ",
      "      ###D###    ",
      "      #.....#    ",
      "      #..$G.#    ",
      "      #.....#    ",
      "      #######    ",
    ],
    doors: [{ x: 9, y: 5, plates: [{ x: 10, y: 2 }] }],
  },
  {
    id: 44,
    name: "Bottleneck",
    objective: "Two crates through a narrow gap.",
    parMoves: 55,
    map: [
      "###########",
      "#@........#",
      "#.$$......#",
      "#.........#",
      "####..#####",
      "#...G.G...#",
      "#.........#",
      "###########",
    ],
  },
  {
    id: 45,
    name: "Frost Relay",
    // Two crystals through one gate into a wide bay (not the L22 ice-runway clone).
    objective: "Open the gate and park both crystals in the bay.",
    parMoves: 55,
    map: [
      "##############",
      "#@...........#",
      "#P.$$........#",
      "#............#",
      "######D#######",
      "#............#",
      "#...G....G...#",
      "#............#",
      "##############",
    ],
    doors: [{ x: 6, y: 4, plates: [{ x: 1, y: 2 }] }],
  },
  {
    id: 46,
    name: "Final Assembly",
    // Spread quartet — not the L29 clump layout.
    objective: "Four crystals. Clear the bay.",
    parMoves: 40,
    map: [
      "##############",
      "#@...........#",
      "#.$..$..$..$.#",
      "#............#",
      "#.G..G..G..G.#",
      "#............#",
      "##############",
    ],
  },
  {
    id: 47,
    name: "Deep Vault",
    objective: "Open the security gate, then park both crystals.",
    parMoves: 70,
    map: [
      "#################",
      "#@..............#",
      "#.$$.......P....#",
      "#...............#",
      "##########D######",
      "#...............#",
      "#.....G.....G...#",
      "#...............#",
      "#################",
    ],
    doors: [{ x: 10, y: 4, plates: [{ x: 11, y: 2 }] }],
  },
  {
    id: 48,
    name: "Masterwork",
    // Finale: plate + portal vault with two crystals (no dry route down).
    objective: "Plate, portal, both crystals. No mistakes.",
    parMoves: 30,
    map: [
      "#################",
      "#@........A.....#",
      "#........P......#",
      "#################",
      "        #B#      ",
      "      ###D###    ",
      "      #.$G$.#    ",
      "      #.....#    ",
      "      #######    ",
    ],
    doors: [{ x: 9, y: 5, plates: [{ x: 9, y: 2 }] }],
  },
];

export function getLevel(id: number): LevelDef | undefined {
  return LEVELS.find((l) => l.id === id);
}

export function chapterOf(id: number): number {
  if (id <= 8) return 1;
  if (id <= 18) return 2;
  if (id <= 28) return 3;
  if (id <= 38) return 4;
  return 5;
}
